<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrmDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sampleEmpIds = [
            '210402', '230501', '191230', '191105', '241101'
        ];

        $sampleEmployeeNames = [
            'Sunarto Sunarto', 'Wahyu AJI PRASETYO', 'Dion Pradana', 'Fedi SANTOSO',
            'Ari RAHWANTO', 'Razali RAZALI', 'Laila Sembiring', 'Sandi Mahendra',
            'Restu Wilujeng', 'Tio Anif', 'Andreas Ginting', 'Wina Wardani',
            'Made YULIASTUTI', 'Citra Retno', 'Riva ANGGRAHENI', 'Rusnadi Rusnadi',
            'Bagus WICAKSONO', 'Sugeng Purnomo', 'Noventy MAULIDA', 'Yayat Mulyat',
            'Devi Opilanty', 'Rangga Putra', 'Yeni Prasetyowati', 'Dian SARI',
            'Gabriella Siregar', 'Dewi Efrina', 'Lia CHRISTANTI', 'Muhammad Syato',
            'Nyoman Alit', 'May Sari', 'Fitria Ningsih', 'Muhammad Amin',
            'Poppy WIDYASARY', 'Rama Rahmanto', 'Budi Rismanto', 'Dody Sunandaka',
            'Miscbah Istichori', 'Ferdinal ARIF', 'Aprilianus Ndruru', 'Hardiyawan SASTRA',
            'Hafiz Hafiz', 'Dito Arjundinto', 'Adhe SAPUTRA', 'Zulhan Sebastian',
            'Novida NOVIDA', 'Bobby Dona', 'Mochamad Wahyudi', 'Arief Priyo',
            'Abdul Hanan', 'Sahida SAHIDA', 'Eka ERNAWATI', 'Moch FARID',
            'Umar PERMANA', 'Dhamas PRADANA', 'Joko Purnomo', 'Wahyuni Arsyad',
            'Dawud Amri', 'Ratna Dewi', 'Angri MUHENDRO', 'Erwanto Mulyono',
            'Mariyah Ulfa', 'Arie WIDODO', 'Dwi Cahyono', 'Heru HANDOKO',
            'Rully Maulana', 'Rifqi Alhamidi', 'Ulfa Afria', 'Wahyu Jatmiko',
            'Indhira Wahyuni', 'Chotif MIFTAH', 'Erwin Purwanto', 'Teguh Juniadi',
            'Bangkit Nasution', 'Pribadi HIDAYAT', 'Ferdiana Sukma', 'Sri Mulyastuti',
            'Rosyid Haryadi', 'Endah Supriyatin', 'Samsuwardi SAMSUWARDI', 'Trya DESYASARI',
            'Hendry Nurhardiyanto', 'Tantyo WIBOWO', 'Vivi YUNATA', 'Tedi BUDIANTO',
            'Nanang Setyawan'
        ];

        $sampleAccounts = [
            '52 BHAKTI DHARMA HUSADA, RSUD', '52 DARUSSYFA, RSI.', '52 INSTALASI RS. BUNDA',
            '52 KUPANG BARU, APT.', '52 LOMBOK DUA DUA LONTAR, RS', '52 MITRA KELUARGA, RS / SURABAYA',
            '52 PELABUHAN, RS., PT.', '52 SBY ORTHOPEDI TRAUMATOLOGY, RS', '52 SINAR HUSADA, APT.',
            '52 WIJAYA, RS.', '52 WIYUNG SEJAHTERA, RS.', 'TIARA, APT. (PT. APOTEK TIARA INDONESIA)',
            'RUMAH SAKIT UMUM PUSAT SURABAYA', '52 NATIONAL HOSPITAL, RS', '54 WALUYO JATI KRAKSAAN, RSUD.',
            'APOTEK KIMIA FARMA (307)', 'APOTEK NUDIYA FARMA', '54 AL-ROHMAH BANYUWANGI, RS',
            '54 ASEMBAGUS, RSUD.', '54 BESUKI, RSUD', '54 BHAYANGKARA BONDOWOSO, RS', '54 GENTENG, RSUD.',
            '54 GRAHA SEHAT, RS', '54 INST FARMASI AL HUDA, RS', '54 INST. FAR. RSUD BLAMBANGAN',
            '52 AL IRSYAD, RS.', '49 MOHAMMAD NOER PAMEKASAN, RSU', '49 DR MOHAMMAD ZYN, RSUD.',
            '49 NINDHITA, RS.', '49 RSUD. DR. H. SLAMET MARTODIRDJO PAMEK', '49 RSUD DR. H. MOH. ANWAR',
            '49 AFIQ FARMA, APT', '49 ASYIFA HUSADA, RS', '49 DR. M. SUWANDHIE, RSUD.',
            '27 ISLAM JAK-UT, RS, APT.', '27 MITRA KELUARGA, RS / KELAPA GADING', '27 PELABUHAN JAKARTA, RS.',
            '27 PORT MEDICAL CENTER, RS.', '27 SATYA NEGARA, RS.', '27 SEHAT SENTOSA, APT',
            '27 SULIANTI SAROSO.RSPI,INST', 'APOTEK NICO SEHAT', 'FIRDAUS, RS (PT PRISINDO MITRA UTAMA)',
            '54 INST. FARM. RSI FATIMAH, RS', '54 INSTALASI FARMASI RS. GRAHA MEDIKA',
            '54 INSTALASI FARMASI RSU. PKU MUHAMMADIYAH', '54 MITRA MEDIKA BONDOWOSO, RS',
            '54 MITRA SEHAT, RS', '54 MOYA FARMA, APT', '54 NAHDLATUL ULAMA, RS',
            '54 PTPN XI (RS. ELIZABETH)', '54 PTPN XII (PT. ROLAS NUSANTARA MEDIKA)',
            '54 RSUD DR. H. KOESNADI BONDOWOSO', 'KARYA SEHAT.APT (JAYA SAKTI MANDIRI )',
            'KIMIA FARMA 350, APT', 'KIMIA FARMA KEBON BAWANG, APT', 'KIMIA FARMA SUNTER, APT',
            'KIMIA FARMA TUGU, APT', 'RUMAH SAKIT UMUM PEKERJA', 'SUNTER INDAH,APT', '27 KOJA, RSUD',
            '27 LIDO, APT.', '27 MEDICA GRIYA, RS., APT.', '27 MITRA KELUARGA KEMAYORAN, RS',
            '47 ISLAM CAWAS, RSKB', '47 ISLAM, RS / KLATEN', '47 KASIH IBU, RS.', '47 KUSTATI RS, APT.',
            '11 DR. FAUZIAH, RSUD', '11 DR. ZUBIR MAHMUD, RSUD', '11 INST. FARMASI RSUD TAMIANG',
            '11 JATIM, APT.', '11 JEUMPA, RS.', 'METHODIST SUSANNA WESLEY, RSU.', '12 HAJI ADAM MALIK. RSUP',
            '12 PAHLAWAN, APT.', '12 PERTAMINA PANGKALAN BRANDAN, RS', '60 SULTAN SYARIF MOHAMAD ALKADRIE, RSUD',
            '60 VINCENTIUS, RSU.', 'KIMIA FARMA, APT ( PT. KIMIA FARMA APOTEK )', 'RS MEDIKA DJAYA',
            '60 ABDUL AZIS, RS.', '56 RSUD DR. SAIFUL ANWAR', '56 SEJATI, APT.',
            '56 UNIVERSITAS MUHAMMADIYAH MALANG, RS',
            'INSTALASI FARMASI RSIA HUSADA BUNDA (PT. HUSADA BUNDA MULIA)', 'KIMIA FARMA 187, APT',
            'KIMIA FARMA NO. 53, APT', 'KIMIAFARMA 245 BATU, APT (PT. KIMIA FARMA APOTEK)',
            'RUMAH SAKIT HERMINA TANGERANG', '56 AVISENA UNISMA, APT.', '17 RIZKI PRATAMA, APT.',
            '17 ROKAN HULU, RSUD.', '17 SANTA MARIA, RS./ PKU',
            'RSAB UJUNG BATU, APT. (PT. AWAL BROS INTAN MEDIKA)', 'APOTEK DOKTER MISBAH 2 (JUNAIDI)',
            'APOTEK HIMALAYA FRMA, APT', 'APOTEK MANDIRI 2', 'APOTEK SENTRAL MEDIKA', 'ASEAN 2, APT.',
            'CEMPAKA, APT. (CV. CEMPAKA)', 'DUNIA SEHAT, APT.', 'KARTIKA, APT. (CV. KARTIKA)',
            'KELUARGA NISA FARMA, APT.', 'KIMIA FARMA NO. 122, APT.',
            'KIMIA FARMA NO. 395, APT. (PT. KIMIA FARMA APOTEK)', 'RS PERTAMINA DUMAI',
            '12 AMANDA MITRA HUSADA, RSU', '12 SUNDARI, RS.', '12 HERMINA, RSU',
            '12 MURNI TEGUH M. HOSPITAL, RS', '12 ADVENT, RS.', 'RUMAH SAKIT UMUM DAERAH PANCUR BATU',
            'KIMIA FARMA , APT / RADJIMAN', 'KIMIA FARMA , APT / VETERAN', 'KIMIA FARMA, APT / SOLO BARU',
            'KIMIA FARMA, APT / SUKOHARJO', 'NURANI, APT (SOL)', 'RS FITRI CHANDRA', 'RS MULIA HATI',
            'RS UMUM PUSAT SOLO', 'TELUKAN FARMA, APT', '47 AKMAL SEHAT, APT', '47 DR. OEN SOLO BARU, RS',
            '58 SURYA HUSADHA, RSU / UBUNG', '58 WANGAYA FARMASI B., RSUD.', 'RS SEMARA RATIH TABANAN',
            'PT. PERTAMEDIKA BALI HOSPITAL', '58 KERTHA USADA FARMA, APT.', '58 MANGUSADA, RSD',
            '36 SUMEDANG, RSU., APT.', '37 PINDAD, RS.', '37 SANTO Y. APOTIK, RS.',
            '37 HERMINA, RS / ARCAMANIK', '37 AMC HOSPITAL, RS.', 'GRHA BUNDA, RSIA',
            '37 HUMANA PRIMA, RSB', '37 KESEHATAN KERJA PROV JAWA BARAT, RSUD', '44 DR. SARDJITO, RSUP',
            '44 SADEWA,RSKIA', '44 JOGJA INTERNATIONAL HOSPITAL', '44 TNI AU DR. S. HARDJOLUKITO,RS',
            '44 UGM, RSA', '44 CONDONG CATUR, RS.', '40 PERS. ST. ELISABETH, RS.', '40 RUMKIT SALATIGA, RS',
            '40 SALATIGA, RS.', '40 TUBERCOLUSA, RS.', '40 UNGARAN, RS.', '40 WILLIAMBOTH, RS.',
            'RSU BANYUMANIK 2', '40 KARIADI, DR., RS.', '30 PONDOK INDAH, RS.',
            '30 SILOAM, RS / SIMATUPANG', '30 SUPER SAVER, APT.', 'KIMIA FARMA 55 OSHCS',
            'KLINIK PRATAMA PERTAMEDIKA SINABUNG',
            'MEDIKA PERMATA HIJAU, RS (PT KHIDMAT PERAWATAN JASA MEDIKA)', '30 AJIWARAS, APT.',
            '30 AMERTA, APT', '30 ASIH EKA ABADI, PT.', '30 DIAGRAM HEALTHCARE IND. PT',
            '30 FATMAWATI, RS.', '30 PRIMAJAYA PUTRA MANDIRI, PT', '30 PURI CINERE RS. APT.',
            '21 BEND PENGGUNA RSUPN CIPTO M', '21 CIKINI, RS., APT.', '21 GATOT SOEBROTO, RSPAD',
            '21 BEDAH ANAK, RSCM.', '21 KRAMAT 128, RS.', '32 KOTA BOGOR, RSUD.',
            '42 RS. HERMINA BITUNG', '42 SILOAM, RS / LIPPO VILLAGE TGR',
            '42 SILOAM, RSU / LIPPO VILLAGE TGR', '42 SUMBER SEHAT/TGR , APT.', '42 TIARA,RS',
            '42 UTAMA SEHAT, APT.', '43 BANTEN, RSUD', '39 MITRA SEJAHTERA, APT',
            '39 MORO AMAN, APT.', '39 MUBAROK 2, APT.', '39 MULUK INDAH, APT.',
            '39 PASUKETAN GUNUNG SARI, APT.', '39 PASUKETAN PERUM, APT', '39 PETRATEAN, APT',
            '39 PRIMA SEJAHTERA, APT.', '39 PUTERA BAHAGIA, RS', '39 SEKAR KAMULYAN, RS.',
            '39 TUNGGAL, APT.', '39 UMC, RSU', '39 UNGU FARMA, APT', '39 AMAN HUSADA 2, APT',
            '39 CAHAYA BUNDA, RSIA', '39 CIREMAI, RS., APT.', '50 ALPEN AGUNGRAYA/SID, PT.',
            '50 DELTA SURYA, RS., APT.', 'MITRA KELUARGA PONDOK TJANDRA, RS', '50 SIDOARJO, RSUD.',
            '50 SITI HADJAR, RSI.', '49 PRIMA HUSADA, RS/PASURUAN', '50 SITI KHODIJAH, RSU., APT.',
            '47 SARILA HUSADA, RS', '47 SOEHADI PRIJONEGORO.,DR, RSUD', '47 YAY. KESEHATAN PANTI KOSALA',
            '59 SILOAM, RSU/ KUPANG', '59 ST. CAROLUS BORROMEUS, RSU', '59 ST. GABRIEL KEWAPANTE, RS',
            '59 T.C. HILLERS MAUMERE, DR.RSUD', '59 UMBU RARA MEHA WAINGAPU, RSUD', '59 WAIKABUBAK, RSUD',
            'RSUP DR BEN MBOI', '59 LEONA, RSU / KUPANG', '59 LINDIMARA, RSK.', '59 ATAMBUA, RSU.',
            '12 MARTHA FRISKA. RSU/MULTATULI', '12 GRANDMED, RS', '12 SANTA ELIZABETH, RSU.',
            '12 BHAYANGKARA MEDAN, RS.', '12 MADANI, RSU', 'COLUMBIA ASIA, RS AKSARA', '12 SRI PAMELA, RSU',
            'Regina Maris, RS', '12 STELLA MARIS. RSIA', '12 COLUMBIA ASIA, RS.', '12 SARAH, RS.',
            '12 SEMBIRING DELITUA. RSU', '12 MARTHA FRISKA, RSU / YOS SUDARSO', '14 HAJI, RS., APT.',
            'APOTEK HALIM', '12 AGE FARMA. APT', '12 AGUNG MULIA. APT', 'AK JAYA, APT',
            'DELI. APT/ L.PAKAM', 'KIMIA FARMA LUBUK PAKAM, APT', 'KIMIA FARMA, APT/ZEIN HAMID',
            'SAUDARA BARU.CV.APT ( CV.APOTIK SAUDARA BARU )', '20 INST.FAR. PALEMBANG, RSMH.',
            '20 INSTALASI FARMASI RS. ISLAM AT-TAQWA', '20 KARYA ASIH CHARITAS, RS/PLG',
            '20 PUSRI, RS., APT.', '20 RIKA AMELIA, RSIA', '20 CHARITAS, RS.',
            '18 SULTAN THAHA SAIFUDIN, RSUD', '18 TAUFIK FARMA, APT', '18 THERESIA, RS., APT.',
            '18 WIDA FARMA, APT', 'APOTEK KIMIA FARMA (JL SKRD. SYAHBUDIN)',
            'APOTEK KIMIA FARMA 117 (JL. KOL. ABUNJANI)', 'CAHAYA SEHAT,APT',
            '34 SILOAM, RS / LIPPO CIKARANG', '34 ANISA I, APT.', '34 AWAL BROS BEKASI TIMUR, RS',
            '58 KARANGASEM, RSUD.', '58 BIMC UBUD, KLINIK', '58 PURI BUNDA TABANAN, RSIA',
            '58 KASIH IBU, RS./INST. FARMASI', '58 KENAK MEDIKA, KLINIK UTAMA', '58 KF 102 KEDIRI, APT.',
            '58 KF 154 GATSU, APT.', '58 KLUNGKUNG, RSUD./INST. FARMASI', '58 NYITDAH, RSUD',
            '24 PURI ADHYA PARAMITA, RSIA', '24 SLARA NIAGA PRIMA, PT.', '24 STANDAR PRIMA MANDIRI, PT',
            '24 URIP SUMOHARJO, RS.', '24 YUKUM MEDICAL CENTER.RS', '20 INST.FARM.RSUD LAHAT',
            '20 PALEMBANG BARI, RSUD.', '20 BUKIT ASAM TANJUNG ENIM, RS',
            '34 MITRA KELUARGA, RS / BKS TIMUR', '34 OMNI PEKAYON, RS', '34 ANANDA, RS.',
            '34 AWAL BROS, RS / BEKASI', '34 BEKASI, RSU., APT.', '68 SAYANG RAKYAT, RSU',
            '68 TADJUDDIN CHALID MAKASSAR,RS', 'RS KHUSUS OTAK & JANTUNG PERTAMINA ROYAL BIRINGKANAYA',
            'RS SENTRA MEDIKA', '66 SILOAM, RS / MANADO', '66 BHAYANGKARA MANADO, RS',
            '66 CHASAN BOESOIRIE TERNATE, RSUD', '34 HERMINA BEKASI, RS',
            '34 SILOAM BEKASI SEPANJANG JAYA, RS', '34 SILOAM BEKASI TIMUR , RS', 'EKA HOSPITAL, BEKASI',
            '42 CENGKARENG, RS., PT.', '42 CINTA KASIH TZU CHI, RS.',
            '42 CIPUTRA HOSPITAL CITRA GARDEN CITY,RS', '42 EMC TANGERANG, RS',
            '42 HERMINA, RS / DAAN MOGOT', '42 MITRA KELUARGA, RSU / KALIDERES', '42 PERUMNAS, APT.',
            '42 SITANALA, RS.', '42 TANGERANG RSU', '42 TIRTA JAYA, APT.', '42 TIRTASARI, APT.',
            '43 CILEGON, RSU', '43 KRAKATAU MEDIKA, PT.', '43 PANDEGLANG, RS.',
            'MANDAYA ROYAL HOSPITAL', 'RS HERMINA PERIUK', 'RS PRIMAYA PASAR KEMIS',
            '21 PURI INDAH, RS.', '21 PURI SATU, APOTIK', '21 PUSKESMAS KEBON JERUK',
            '21 PUSKESMAS KECAMATAN PALMERAH', '21 PUSKESMAS KEMBANGAN', '21 ROXY TANJUNG DUREN, APT.',
            '21 ROYAL TARUMA, RS.', '21 SILOAM, RS / KEBON JERUK', '21 SIMPANG PURI, APT.',
            'MATAHARI, APT. (GRAHASEHAT FARMATAMA, PT.)', 'SUPER SAVER, APT (PT. MEDICINE PLUS INDONESIA)',
            'UKRIDA, RS.', 'ZENITH HEALTHCARE, APT.', '21 ANGGREK MAS, RSU.', '21 BUGAR, APT',
            '21 DR SOEHARTO HEERDJAN, RSJ', '21 GRHA KEDOYA, RSB', '21 HARAPAN KITA, RSAB.',
            '21 HOSANA 1, APT.', '21 K24 PESANGGRAHAN', '21 KANKER DHARMAIS, RS.',
            '21 KEMBANGAN, RSUD.', '21 MANJUR, TO./KEMBANGAN TIMUR', '21 PELNI PETAMBURAN, RS.',
            '66 KANDOU PROF. DR./MALAYANG RS.', '66 KOTA TIDORE KEPULAUAN, RSD', '66 LABUHA, RSUD',
            '66 TKT. III 07.06.01 R.W. MONGISIDI, RS', '66 TOBELO, RSUD', '68 BULUKUMBA, RSU.',
            'RUMAH SAKIT HERMINA MANADO', '68 INST.RSUD.BANTAENG', '68 LANTO DAENG PASEWANG',
            '68 PERJAN WAHIDIN S., DR., RS.', '20 INST. FARM. RSUD MUARA ENIM', '20 APOTEK ASIA',
            '20 BAKTI TIMAH, RS.', '20 CHARITAS, RS. / PALEMBANG', '20 MUHAMMADIYAH, RS.',
            '20 PELABUHAN/BOOM BARU, RS.', '32 BINA HUSADA, RS., APT.', '32 CIBINONG, RSUD',
            '32 CIPTA SUKSES MEDIKA, PT', '32 CITRA INSANI, APT.', '32 DAYA HIDUP SEMESTA, PT.',
            '32 EKA HOSPITAL, RS', '32 EMC SENTUL, RS', '32 HERMINA RS/MEKARSARI', '32 I.F. F.M.C., RS.',
            '32 INST. FARMASI CILEUNGSI, RSUD', '32 ISLAM AYSHA, RS',
            '32 KIMIA FARMA, PT./ KF 7, APT.', '32 M.H. THAMRIN, RS.', '32 MARY CILEUNGSI HIJAU, RS',
            '32 MULIA PAJAJARAN, RS', '32 PERMATA JONGGOL, RS', '32 PERMATA PERTIWI, RSIA',
            '32 RUMAH SEHAT TERPADU.D.D, RS', '32 SENTOSA, RSIA/KEMANG.', '32 SENTRA MEDIKA, RS',
            '32 SILOAM HOSPITALS BOGOR', '32 TRIMITRA, RS.', 'BELVARA ANUGERAH PERSADA, PT',
            '32 AZRA, RS., APT.', '30 AMINAH, RS.', '30 BHAKTI ASIH, RS.', '30 ANAKKU, APT.',
            '30 CHICO, APT.', '30 CINTA KASIH, RB.', '30 DHIA, RSIA', '30 DR. SUYOTO, RS',
            '30 HERMINA, RS / CIPUTAT', '30 HERMINA, RS / SERPONG', '30 K-24 BINTARO SEKTOR 5',
            '30 K-24 BINTARO SEKTOR 9, APT', '30 KARUNIA PUSPITA, PT./CIRENDEU, APT.',
            '30 KAWI JAYA, APT./BINTARO', '30 KAWI JAYA, APT./PAMULANG', '30 KEHAMILAN SEHAT CEGER, APT',
            '30 KIMIA FARMA NO. 219, APT', '30 KIMIA FARMA, PT. (267)',
            '30 KOTA TANGERANG SELATAN, RSU (APBD)', '30 MEDIKA LESTARI, RS', '30 METROMEDIKA, APT.',
            '30 MITRA KELUARGA BINTARO, RS', '30 PREMIER, RS / BINTARO', '30 MOSE, APT.', '30 MULYA, RSU.',
            'RS, HERMINA CILEDUG', '30 NIDEA, APT.', '30 OLAF, APT.', '30 PANCABALA JAYA MAKMUR, PT',
            '30 PERMATA IBU, RS', '30 PESANGGRAHAN, RSUD (BEND)', '30 PONDOK INDAH, RS / BINTARO JAYA',
            '30 PUSPITA PERMATA, PT.', '30 ROXY, APT / CILEDUG', '30 SYAHID, RS',
            '30 TAMAN K. JERUK, APT.', 'BINTARO WOMEN AND CHILDREN CLINIC ,APOTIK',
            'CAHAYA, APT (CV. CAHAYA)', 'FARMARIN, APT/BINTARO (PT. FAJAR FARMATAMA)',
            'K-24 FIERA BOULEVARD, APT', 'KASUARI ,APT (CV KASUARI ADITYA JAYA)', 'KEBAYORAN LAMA, RSUD',
            '20 PERTAMINA, RS, / PLAJU PALEMBANG', '20 SILOAM, RS / SRIWIJAYA PLG',
            '20 DEMPO DJAYA, PT.', '20 DEPATI HAMZAH, RSUD', '20 SILOAM, RS /BANGKA',
            '20 SUNGAI KUNDUR, RSK.', 'HERMINA, RS / OPI JAKABARING',
            '16 INS FARMASI RSUD SEI DAREH,APT', '16 INST RSUD SIJUNJUNG', '16 KPN. RSUD SULIKI, APT.',
            '16 PADANG PANJANG, RSUD', '16 RSUD DR. ACHMAD MOCHTAR BUKITTINGGI', '16 STROKE NASIONAL, RS.',
            'INSTALASI RSUD LUBUK SIKAPING ( RSUD LUBUK SIKAPING )', 'RSU Madina Bukittinggi',
            'RSUD PROF. DR. M A HANAFIAH SM', 'SUKMA BUNDA RSKIA', '16 ADNAAN WD., DR., RSU., APT.',
            '16 IBNU SINA , RS. / PDG BUKIT TINGGI 1', '16 IBNU SINA PANTI, RSI / PDG LUBUK SIKAPING',
            '16 IBNU SINA, RSI./ PDG PADANG PANJANG', '16 IBNU SINA, RSI./PDG PAYAKUMBUH',
            '34 LIRA MEDIKA, RSU', 'PRIMAYA HOSPITAL KARAWANG', 'RS. HERMINA KARAWANG',
            '34 SILOAM, RS / PURWAKARTA', 'RS MANDAYA KARAWANG', '34 DEWI SRI, RSU.',
            '34 DR. DJOKO PRAMONO, RSIA', '34 HELSA, RS', '34 IZZA, RSU', '34 KARAWANG KAB., RSU.',
            '34 KENCANA JAYA, APT', '34 KIDANG RANGGA, APT', '34 BHAKTI HUSADA, RS., APT.',
            '34 CIBITUNG, KAB, RSU.', '34 DIO FARMA, APT', '34 GRAHA JUANDA, RS', '34 GRHA MM2100, RS',
            '34 HERMINA GRAND WISATA, RS', '34 K-24 ANGGREK CKR BARU, APT.', '34 K-24 CIKARANG, APT',
            '34 MEDIROSSA, RS', '34 MITRA KELUARGA, RS / CIKARANG', '34 OMNI CIKARANG, RS',
            '34 PERMATA KELUARGA JABABEKA, RS', '34 RIDHOKA SALMA, RS',
            '34 RS. PERMATA KELUARGA LIPPO CIKARANG', '34 SENTRA MEDIKA, RS',
            'KARYA MEDIKA II, RS (PT ADHIFARMA ADYAJAYA MEDICA)', 'KIMA FARMA, APT/TAMBUN',
            'KIMIA FARMA CAHAYA AMALIA, APT', 'KIMIA FARMA PASADENA, APT',
            'KIMIA FARMA SUKARESMI, APT/CIBARUSAH', 'KIMIA FARMA ZAMRUD 2, APT',
            'KIMIA FARMA, APT/ GRAND WISATA', 'KIMIA FARMA, APT/ KF 340', 'KIMIA FARMA, APT/PILAR MAS',
            'MITRA KELUARGA, RS / GRAND WISATA', 'RS HERMINA METLAND CIBITUNG',
            '31 HERMINA DEPOK, RSIA.', '31 PERMATA CIBUBUR, RSIA.', '31 SENTRA MEDICA, RS.',
            'INST. LUBUK BASUNG RSUD', 'RSUD DR. RASIDIN PADANG', '16 AISYIYAH RS PARIAMAN',
            '16 Al-IHSAN RSIA', '16 BKM RSU, APT', '16 HERMINA PADANG, RS',
            '16 IBNU SINA, RSI./ PDG GAJAH MADA SITEBA', '16 IBNU SINA, RSI./ PDG PASAMAN',
            '16 MUHAMMAD ZAIN, DR., RSUD.', '16 TAMAR MEDICAL CENTRE, RS',
            '24 MUHAMMADIYAH METRO.RSU', '24 MUTIARA HATI, RB.', '24 PANTI SECANTI, RB.',
            '24 PURI BETIK HATI, RSIA', '24 SANTA ANNA, RSIA', '24 SUKA DANA, RS.', 'WAY KANAN, RSUD.',
            '24 AHMAD YANI, RSU.', '24 ANUGRAH MEDIKA, RSIA', '24 BUMI WARAS, RS., APT.',
            '24 GRAHA HUSADA, RS.', '24 IMANUEL, RS.', '24 INST.FARMASI MARDI W., RS.',
            '24 INSTALASI FARMASI RSIA BELLEZA KEDATON', '24 KARTINI, RS', '24 LIWA, RSU.',
            '24 MITRA HUSADA, RS', 'APT. KIMIA FARMA 491 SAWANGAN', 'K24 PEKAPURAN, APT',
            'KIMIA FARMA 202 KEJAYAAN, APT'
        ];

        $sampleContactNames = [
            'Reni Reni_ID20800', 'Rohmatulloh Rohmatulloh_ID12374', 'Yanuar Yanuar_ID21323',
            'Yoga Yoga_ID00458', 'Brilliant Citra_ID39660', 'Chairan Nurprasetya_ID35823',
            'Fitria Kusuma_ID35293', 'Ismu Nugroho_ID35824', 'Nur Suci_ID22243',
            'Reny Lestari_ID10789', 'Rini Yulianti_ID12631', 'Ruliyah Ruliyah_ID13552',
            'Dwita Saraswati_ID24403', 'Francisca Francisca_ID01400', 'Fredy Yumingto_ID21345',
            'Andry Sultana_ID01925', 'Boedi Tedjo_ID11058', 'Djohan Wirawan_ID14769',
            'Dwi Meinindah_ID07393', 'Erwin Rahmawan_ID18401', 'Ery Karinawati_ID31694',
            'Hanna Hanna_ID03054', 'Hendra Hadiwijaya_ID12324', 'Lewis Lie_ID00933',
            'Lie Venny_ID38235', 'Nario Gunawan_ID08679', 'Paulus Sugiyanto_ID12141',
            'Yosis Y.Matulo_ID16953', 'ANGGER ANGGER_ID11119', 'Carlos Gracia_ID04247',
            'Cicilia Mayasari_ID02034', 'Ditya Marta_ID39662', 'Gede Chandra_ID07334',
            'hasan Wijaya_ID10912', 'Henry Ricardo_ID06507', 'Inez Iem_ID17611',
            'Jhosepin Jhosepin_ID31699', 'Komang Agung_ID11072', 'Luh Gede Anggita_ID11005',
            'Nyoman Dewi_ID14339', 'Only Taylor_ID31710', 'Tanjung Sangkai_ID22006',
            'Therri Effendi_ID19603', 'Devy Rindiyawuni_ID24402', 'Linda Murniati_ID24401',
            'Budi Wicaksono_ID19856', 'Darning Darning_ID35294', 'Herry wibowo_ID05044',
            'I wayan Harnaya_ID11665', 'Lisna Farida_ID17312', 'Abdul Latif_ID31673',
            'Achmad Hendra_ID00773', 'Aries Hidayat_ID31677', 'Astik Kurdi_ID22206',
            'Didyn Nuzul_ID39661', 'Dinik Purwahyuningsih_ID21483', 'Farid Himawan_ID09632',
            'Fenny Mulyati_ID14655', 'hengky hengky_ID13923', 'Hermanto Putra_ID19189',
            'Junaidi Junaidi_ID17577', 'Khoirunnisa Novitasari_ID39553', 'Ninuk Ariningtyas_ID21188',
            'Putra Parlindungan _ID03542', 'Endang Wulandari_ID24399', 'Liliek Liliek_ID24398',
            'Adya Jati_ID40925', 'Andy Wirjodigdo_ID40924', 'Azmi Farhadi_ID40921',
            'Haris Khoirur_ID40922', 'Larona Hydravianto_ID40920', 'Laskar Pradnyan_ID40919',
            'Muhammad Avicenna_ID40923', 'Sunadji Sunadji_ID14517', 'Syahrudi Syahrudi_ID15685',
            'Totok Mardiyanto_ID01212', 'Yenti Yenti_ID30779', 'Nudiya A_ID34210',
            'Niken Niken_ID03886', 'IGN Bagus Andhika Pramana_ID39827', 'Lilys Suzanna_ID34186',
            'Tofan Margaret Dwi Syahputra_ID18999', 'Jefri Jefri_ID02261', 'Rafika Rafika_ID19249',
            'Rudi Dewantara_ID04839', 'Adith Fileanigraha_ID12993', 'Agus Agus_ID04085',
            'Nolly Kiki, Sp.OT_ID09782', 'Nurul Huda Didiek_ID16362', 'Nyoman Nyoman_ID09591',
            'Risandi Risandi_ID18163', 'Subhkan Subhkan_ID05309', 'Erni Erni_ID07169',
            'Antoni Yusbida_ID12910', 'Fafa Fafa_ID13643', 'Novan Affandy_ID22513',
            'Robith Tamara_ID35443', 'Sakinah Sakinah_ID35444', 'Tantri Tantri_ID35442',
            'Wasilul Sp. OG_ID21088'
        ];

        $data = [];
        for ($i = 0; $i < 500; $i++) { // Generate 500 dummy records
            $data[] = [
                'year' => rand(2020, 2025),
                'month' => rand(1, 12),
                'employee_name' => $sampleEmployeeNames[array_rand($sampleEmployeeNames)],
                'contact_name' => $sampleContactNames[array_rand($sampleContactNames)],
                'account' => $sampleAccounts[array_rand($sampleAccounts)],
                'contact_categorization' => ['D', 'A', 'B', 'C'][array_rand(['D', 'A', 'B', 'C'])],
                'target_call' => rand(0, 5),
                'target_coverage' => rand(0, 10),
                'specialty_id' => rand(0, 10),
                'specialty' => ['PHY', 'GP', 'ORT', 'BDH', 'OTH', 'OBG', 'INT', 'NUR'][array_rand(['PHY', 'GP', 'ORT', 'BDH', 'OTH', 'OBG', 'INT', 'NUR'])],
                'area_id' => rand(0, 10),
                'area' => ['Medical', 'Pharmacy', 'Business'][array_rand(['Medical', 'Pharmacy', 'Business'])],
                'department_id' => rand(0, 10),
                'department' => 'Department ' . rand(1, 10),
                'role_id' => rand(0, 10),
                'role' => ['Specialist', 'Professional', 'Surgeon', 'Nurse', 'Doctor', 'Therapist'][array_rand(['Specialist', 'Professional', 'Surgeon', 'Nurse', 'Doctor', 'Therapist'])],
                'level_id' => rand(0, 10),
                'level_contact' => ['Employee', 'Head of account', 'Head of team', 'Head of department'][array_rand(['Employee', 'Head of account', 'Head of team', 'Head of department'])],
                'unit_id' => rand(0, 10),
                'unit' => ['IGD', 'PHARMACY', 'POLI BEDAH', 'POLI OBGYN', 'POLI ORTHO', 'ICU'][array_rand(['IGD', 'PHARMACY', 'POLI BEDAH', 'POLI OBGYN', 'POLI ORTHO', 'ICU'])],
                'category_id' => rand(0, 10),
                'category' => ['Ambassador(B)', 'User(D)', 'Decision Maker(A)', 'Gate Keeper(C)'][array_rand(['Ambassador(B)', 'User(D)', 'Decision Maker(A)', 'Gate Keeper(C)'])],
                'out_of_town' => (bool)rand(0, 1),
                'ps_name' => 'PS Name ' . ($i + 1),
                'branch_short_name' => ['SBY', 'JKT', 'BDG'][array_rand(['SBY', 'JKT', 'BDG'])],
                'refer_code' => 'REF' . str_pad($i + 1, 3, '0', STR_PAD_LEFT),
                'account_number' => 'ACC' . str_pad($i + 1, 5, '0', STR_PAD_LEFT),
                'specialty_hcp' => 'Specialty HCP ' . ($i + 1),
                'notes' => 'Notes for entry ' . ($i + 1),
                'emp_id' => $sampleEmpIds[array_rand($sampleEmpIds)], // Refactored line
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ];
        }

        // Chunk the data to avoid memory issues for large datasets
        foreach (array_chunk($data, 500) as $chunk) {
            DB::table('crm_details')->insert($chunk);
        }
    }
}