<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrmHeadersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 299,
                'SAPID' => 99903107,
                'empID' => '191207',
                'PSName' => 'Sugeng Purnomo Slamet',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 462,
                'managerName' => 'Andreas Wawan Sunarko',
                'branchID' => 55,
                'station' => 'Jakarta 1',
                'joinDate' => '2005-04-01',
                'email' => 'Sugeng.Purnomo@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'JK1A',
                'areaCode' => 18,
                'areaName' => 'EASTERN JAKARTA',
                'sales_hirearchy' => 'Area 18 - EASTERN JAKARTA',
                'D365_username' => 'Sugeng Purnomo',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 301,
                'SAPID' => 99903160,
                'empID' => '191204',
                'PSName' => 'Zulhan Sebastian',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 3,
                'station' => 'Padang',
                'joinDate' => '2003-08-02',
                'email' => 'Zulhan.Sebastian@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PDG',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Zulhan Sebastian',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 304,
                'SAPID' => 99903213,
                'empID' => '191258',
                'PSName' => 'Budi Rismanto',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 464,
                'managerName' => 'Pradana Budiyanto',
                'branchID' => 10,
                'station' => 'Jakarta 1',
                'joinDate' => '2014-11-01',
                'email' => 'Budi.Rismanto@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'JK1',
                'areaCode' => 19,
                'areaName' => 'WESTERN JAKARTA',
                'sales_hirearchy' => 'Area 19 - WESTERN JAKARTA',
                'D365_username' => 'Budi Rismanto',
                'distID' => NULL,
                'distName' => NULL
            ],
            [
                'id' => 307,
                'SAPID' => 99903096,
                'empID' => '191295',
                'PSName' => 'Rully Maulana',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 543,
                'managerName' => 'Yudhistira Adam Rizaldy',
                'branchID' => 36,
                'station' => 'Yogyakarta',
                'joinDate' => '2018-09-17',
                'email' => 'Rully.Maulana@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'YOG',
                'areaCode' => 9,
                'areaName' => 'SOUTHERN CENTRAL JAVA',
                'sales_hirearchy' => 'Area 09 - SOUTHERN CENTRAL JAVA',
                'D365_username' => 'Rully Maulana',
                'distID' => 1,
                'distName' => 'AAM',
            ],
            [
                'id' => 310,
                'SAPID' => 99903287,
                'empID' => '191283',
                'PSName' => 'Yayat Mulyat',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 464,
                'managerName' => 'Pradana Budiyanto',
                'branchID' => 28,
                'station' => 'Tangerang',
                'joinDate' => '2017-08-01',
                'email' => 'Yayat.Mulyat@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'TGR',
                'areaCode' => 19,
                'areaName' => 'WESTERN JAKARTA',
                'sales_hirearchy' => 'Area 19 - WESTERN JAKARTA',
                'D365_username' => 'Yayat Mulyat',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 326,
                'SAPID' => 99903083,
                'empID' => '191219',
                'PSName' => 'Arief Priyo Purwanto',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 472,
                'managerName' => 'Sandi Nugraha',
                'branchID' => 33,
                'station' => 'Cirebon',
                'joinDate' => '2010-12-27',
                'email' => 'Arief.Priyo@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'CRB',
                'areaCode' => 7,
                'areaName' => 'WEST JAVA',
                'sales_hirearchy' => 'Area 07 - WEST JAVA',
                'D365_username' => 'Arief Priyo',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 327,
                'SAPID' => 99903084,
                'empID' => '191296',
                'PSName' => 'Fara Lisnawati',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 468,
                'managerName' => 'Ika Kurniawati',
                'branchID' => 34,
                'station' => 'Semarang',
                'joinDate' => '2018-10-01',
                'email' => 'Fara.Lisnawati@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'SMG',
                'areaCode' => 8,
                'areaName' => 'NORTHERN CENTRAL JAVA',
                'sales_hirearchy' => 'Area 08 - NORTHERN CENTRAL JAVA',
                'D365_username' => 'Fara Lisnawati',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 328,
                'SAPID' => 99903085,
                'empID' => '191205',
                'PSName' => 'Sri Mulyastuti',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 468,
                'managerName' => 'Ika Kurniawati',
                'branchID' => 37,
                'station' => 'Purwokerto',
                'joinDate' => '2004-01-02',
                'email' => 'Sri.Mulyastuti@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PWK',
                'areaCode' => 8,
                'areaName' => 'NORTHERN CENTRAL JAVA',
                'sales_hirearchy' => 'Area 08 - NORTHERN CENTRAL JAVA',
                'D365_username' => 'Sri Mulyastuti',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 329,
                'SAPID' => 99903087,
                'empID' => '191214',
                'PSName' => 'Joko Heru Purnomo',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 468,
                'managerName' => 'Ika Kurniawati',
                'branchID' => 38,
                'station' => 'Tegal',
                'joinDate' => '2009-07-01',
                'email' => 'Joko.Purnomo@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'TGL',
                'areaCode' => 8,
                'areaName' => 'NORTHERN CENTRAL JAVA',
                'sales_hirearchy' => 'Area 08 - NORTHERN CENTRAL JAVA',
                'D365_username' => 'Joko Purnomo',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 331,
                'SAPID' => 99903093,
                'empID' => '191215',
                'PSName' => 'Andy Ari Wibowo',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 6,
                'managerName' => 'Ari Santoso',
                'branchID' => 47,
                'station' => 'Surabaya',
                'joinDate' => '2009-12-01',
                'email' => 'Andy.Wibowo@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'SBY',
                'areaCode' => 10,
                'areaName' => 'NORTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 10 - NORTHERN EAST JAVA',
                'D365_username' => 'Andy Wibowo',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 334,
                'SAPID' => 99903100,
                'empID' => '191249',
                'PSName' => 'I Nyoman Alit Swastawan Widjaya',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 8,
                'managerName' => 'I Gede Suar Sedana',
                'branchID' => 18,
                'station' => 'Denpasar',
                'joinDate' => '2014-01-04',
                'email' => 'Nyoman.Alit@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'DPS',
                'areaCode' => 12,
                'areaName' => 'BALI-NUSRA',
                'sales_hirearchy' => 'Area 12 - BALI-NUSRA',
                'D365_username' => 'Nyoman Alit',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 336,
                'SAPID' => 99903125,
                'empID' => '191279',
                'PSName' => 'Misbah Istichori',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 462,
                'managerName' => 'Andreas Wawan Sunarko',
                'branchID' => 27,
                'station' => 'Jakarta 3',
                'joinDate' => '2017-04-01',
                'email' => 'Miscbah.Istichori@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'JK3',
                'areaCode' => 18,
                'areaName' => 'EASTERN JAKARTA',
                'sales_hirearchy' => 'Area 18 - EASTERN JAKARTA',
                'D365_username' => 'Miscbah Istichori',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 338,
                'SAPID' => 99903105,
                'empID' => '191285',
                'PSName' => 'Hendry Nurhardiyanto',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 9,
                'managerName' => 'Farid Darojad',
                'branchID' => 16,
                'station' => 'Ponorogo',
                'joinDate' => '2017-09-11',
                'email' => 'Hendry.Nurhardiyanto@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'KDR',
                'areaCode' => 11,
                'areaName' => 'SOUTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 11 - SOUTHERN EAST JAVA',
                'D365_username' => 'Hendry Nurhardiyanto',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 341,
                'SAPID' => 99903109,
                'empID' => '191233',
                'PSName' => 'Ratna Dewi Iswulandari',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 6,
                'managerName' => 'Ari Santoso',
                'branchID' => 47,
                'station' => 'Surabaya',
                'joinDate' => '2012-11-01',
                'email' => 'Ratna.Dewi@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'SBY',
                'areaCode' => 10,
                'areaName' => 'NORTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 10 - NORTHERN EAST JAVA',
                'D365_username' => 'Ratna Dewi',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 343,
                'SAPID' => 99903116,
                'empID' => '191225',
                'PSName' => 'Bobby Aprisan Dona',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 5,
                'station' => 'Bengkulu',
                'joinDate' => '2011-08-08',
                'email' => 'Bobby.Dona@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PLG',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Bobby Dona',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 349,
                'SAPID' => 99903135,
                'empID' => '191246',
                'PSName' => 'Dewi Efrina',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 5,
                'station' => 'Palembang',
                'joinDate' => '2013-08-01',
                'email' => 'Dewi.Efrina@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PLG',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Dewi Efrina',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 350,
                'SAPID' => 99903141,
                'empID' => '191272',
                'PSName' => 'Sandi Mahendra',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 589,
                'managerName' => 'Muhamad Arifin',
                'branchID' => 21,
                'station' => 'Pontianak',
                'joinDate' => '2016-04-18',
                'email' => 'Sandi.Mahendra@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PTK',
                'areaCode' => 13,
                'areaName' => 'KALIMANTAN',
                'sales_hirearchy' => 'Area 13 - KALIMANTAN',
                'D365_username' => 'Sandi Mahendra',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 351,
                'SAPID' => 99903142,
                'empID' => '191255',
                'PSName' => 'Andreas Brema Ginting',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 572,
                'managerName' => 'Prastiajy andika ERIKAYATI',
                'branchID' => 25,
                'station' => 'Medan',
                'joinDate' => '2014-07-01',
                'email' => 'Andreas.Ginting@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'MDN',
                'areaCode' => 16,
                'areaName' => 'NORTHERN SUMATRA',
                'sales_hirearchy' => 'Area 16 - NORTHERN SUMATRA',
                'D365_username' => 'Andreas Ginting',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 352,
                'SAPID' => 99903143,
                'empID' => '191230',
                'PSName' => 'Laila Julfina Sembiring',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 572,
                'managerName' => 'Prastiajy andika ERIKAYATI',
                'branchID' => 25,
                'station' => 'Medan',
                'joinDate' => '2012-04-04',
                'email' => 'Laila.Sembiring@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'MDN',
                'areaCode' => 16,
                'areaName' => 'NORTHERN SUMATRA',
                'sales_hirearchy' => 'Area 16 - NORTHERN SUMATRA',
                'D365_username' => 'Laila Sembiring',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 353,
                'SAPID' => 99903144,
                'empID' => '191293',
                'PSName' => 'Rosyid Haryadi',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 9,
                'managerName' => 'Farid Darojad',
                'branchID' => 16,
                'station' => 'Madiun',
                'joinDate' => '2018-08-01',
                'email' => 'Rosyid.Haryadi@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'KDR',
                'areaCode' => 11,
                'areaName' => 'SOUTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 11 - SOUTHERN EAST JAVA',
                'D365_username' => 'Rosyid Haryadi',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 358,
                'SAPID' => 99903153,
                'empID' => '191290',
                'PSName' => 'Teguh Juniadi',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 9,
                'managerName' => 'Farid Darojad',
                'branchID' => 15,
                'station' => 'Malang',
                'joinDate' => '2017-11-13',
                'email' => 'Teguh.Juniadi@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'MLG',
                'areaCode' => 11,
                'areaName' => 'SOUTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 11 - SOUTHERN EAST JAVA',
                'D365_username' => 'Teguh Juniadi',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 360,
                'SAPID' => 99903155,
                'empID' => '191237',
                'PSName' => 'Gabriella Syani Siregar',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 572,
                'managerName' => 'Prastiajy andika ERIKAYATI',
                'branchID' => 25,
                'station' => 'Medan',
                'joinDate' => '2013-02-01',
                'email' => 'Gabriella.Siregar@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'MDN',
                'areaCode' => 16,
                'areaName' => 'NORTHERN SUMATRA',
                'sales_hirearchy' => 'Area 16 - NORTHERN SUMATRA',
                'D365_username' => 'Gabriella Siregar',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 361,
                'SAPID' => 99903158,
                'empID' => '191256',
                'PSName' => 'Hafiz',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 3,
                'station' => 'Padang',
                'joinDate' => '2014-08-20',
                'email' => 'Hafiz.Hafiz@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PDG',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Hafiz Hafiz',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 364,
                'SAPID' => 99903163,
                'empID' => '191242',
                'PSName' => 'Rangga Laksana Putra',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 6,
                'managerName' => 'Ari Santoso',
                'branchID' => 47,
                'station' => 'Surabaya',
                'joinDate' => '2013-04-22',
                'email' => 'Rangga.Putra@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'SBY',
                'areaCode' => 10,
                'areaName' => 'NORTHERN EAST JAVA',
                'sales_hirearchy' => 'Area 10 - NORTHERN EAST JAVA',
                'D365_username' => 'Rangga Putra',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 368,
                'SAPID' => 99903171,
                'empID' => '191276',
                'PSName' => 'M Dito Arjundinto',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 9,
                'station' => 'Lampung',
                'joinDate' => '2016-11-01',
                'email' => 'Dito.Arjundinto@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'BDL',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Dito Arjundinto',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 369,
                'SAPID' => 99903173,
                'empID' => '191267',
                'PSName' => 'Aprilianus Ndruru',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 462,
                'managerName' => 'Andreas Wawan Sunarko',
                'branchID' => 31,
                'station' => 'Karawang',
                'joinDate' => '2015-11-25',
                'email' => 'Aprilianus.Ndruru@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'BKS',
                'areaCode' => 18,
                'areaName' => 'EASTERN JAKARTA',
                'sales_hirearchy' => 'Area 18 - EASTERN JAKARTA',
                'D365_username' => 'Aprilianus Ndruru',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 376,
                'SAPID' => 99903184,
                'empID' => '191224',
                'PSName' => 'Dwi Cahyono',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 468,
                'managerName' => 'Ika Kurniawati',
                'branchID' => 34,
                'station' => 'Semarang',
                'joinDate' => '2011-08-01',
                'email' => 'Dwi.Cahyono@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'SMG',
                'areaCode' => 8,
                'areaName' => 'NORTHERN CENTRAL JAVA',
                'sales_hirearchy' => 'Area 08 - NORTHERN CENTRAL JAVA',
                'D365_username' => 'Dwi Cahyono',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 378,
                'SAPID' => 99903099,
                'empID' => '191259',
                'PSName' => 'Agustinus Susanto',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 387,
                'managerName' => 'Syariy Threeutami',
                'branchID' => 39,
                'station' => 'Makassar',
                'joinDate' => '2014-11-10',
                'email' => 'Agustinus.Susanto@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'MKS',
                'areaCode' => 14,
                'areaName' => 'FAR EAST',
                'sales_hirearchy' => 'Area 14 - FAR EAST',
                'D365_username' => 'Agustinus Susanto',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 379,
                'SAPID' => 99903192,
                'empID' => '191232',
                'PSName' => 'Fitria Ningsih',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 481,
                'managerName' => 'Wisnu Rangga',
                'branchID' => 5,
                'station' => 'Palembang',
                'joinDate' => '2012-07-02',
                'email' => 'Fitria.Ningsih@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'PLG',
                'areaCode' => 17,
                'areaName' => 'SOUTHERN SUMATRA',
                'sales_hirearchy' => 'Area 17 - SOUTHERN SUMATRA',
                'D365_username' => 'Fitria Ningsih',
                'distID' => NULL,
                'distName' => NULL,
            ],
            [
                'id' => 382,
                'SAPID' => 99903197,
                'empID' => '191292',
                'PSName' => 'Muhammad Syato',
                'flagActive' => true,
                'positionID' => 6,
                'positionName' => 'PSR Reguler',
                'managerID' => 462,
                'managerName' => 'Andreas Wawan Sunarko',
                'branchID' => 31,
                'station' => 'Bekasi',
                'joinDate' => '2018-05-02',
                'email' => 'Muhammad.Syato@essity.com',
                'resignDate' => NULL,
                'branchShortName' => 'BKS',
                'areaCode' => 18,
                'areaName' => 'EASTERN JAKARTA',
                'sales_hirearchy' => 'Area 18 - EASTERN JAKARTA',
                'D365_username' => 'Muhammad Syato',
                'distID' => NULL,
                'distName' => NULL,
            ],
        ];
        $data = array_map(function($item) {
            $item['created_at'] = Carbon::now();
            $item['updated_at'] = Carbon::now();
            return $item;
        }, $data);

        // Chunk the data to avoid memory issues for large datasets
        foreach (array_chunk($data, 1000) as $chunk) {
            DB::table('crm_headers')->insert($chunk);
        }
    }
}
